In [1]:
from sqlalchemy import create_engine, MetaData, Table, inspect
import pandas as pd

def db2pd(file_path):
    # Create a connection to the SQLite database
    engine = create_engine(f'sqlite:///{file_path}')
    # engine = create_engine('sqlite://///workspace/gmo_data/ratest_rate/2023-08-20_ratest_rate.db')

    inspector = inspect(engine)
    table_names = inspector.get_table_names()[0]

    # Reflect the trading_history table
    metadata = MetaData()
    trading_history = Table(table_names, metadata, autoload=True, autoload_with=engine)

    # Query all rows of the table
    results = engine.execute(trading_history.select()).fetchall()

    # Convert results to a list of dictionaries for easy viewing
    rows = [dict(row) for row in results]

    # Convert the list of dictionaries to a pandas DataFrame
    df_trading_history = pd.DataFrame(rows).drop('id',axis=1)

    return df_trading_history

# db2pd('/workspace/gmo_data/trading_hist/2023-08-19_trading_hist.db')
# db2pd('/workspace/gmo_data/ratest_rate/2023-08-20_ratest_rate.db')

In [4]:
from sqlalchemy import create_engine, MetaData, Table
import pandas as pd

# Create a connection to the SQLite database
engine = create_engine('sqlite:////workspace/gmo_data/board/2023-08-17_board.db')

# Reflect the asks and bids tables
metadata = MetaData()
asks_table = Table('asks', metadata, autoload=True, autoload_with=engine)
bids_table = Table('bids', metadata, autoload=True, autoload_with=engine)

# Query data from the asks table
asks_data = engine.execute(asks_table.select()).fetchall()

# Query data from the bids table
bids_data = engine.execute(bids_table.select()).fetchall()

# Convert results to a list of dictionaries for easy viewing (optional)
asks_rows = [dict(row) for row in asks_data]
bids_rows = [dict(row) for row in bids_data]

In [8]:
asks = pd.DataFrame(asks_rows).drop('id',axis=1)
asks

bids = pd.DataFrame(bids_rows).drop('id',axis=1)
bids

            price    size     board_data_responsetime
0       4198000.0  0.0100  2023-08-17 12:12:43.568000
1       4197878.0  0.0033  2023-08-17 12:12:43.568000
2       4197166.0  0.0100  2023-08-17 12:12:43.568000
3       4197165.0  0.0100  2023-08-17 12:12:43.568000
4       4196770.0  0.1500  2023-08-17 12:12:43.568000
...           ...     ...                         ...
179995  3991280.0  0.0200  2023-08-17 23:59:56.994000
179996  3991000.0  0.1000  2023-08-17 23:59:56.994000
179997  3990001.0  0.0500  2023-08-17 23:59:56.994000
179998  3990000.0  1.0587  2023-08-17 23:59:56.994000
179999  3989000.0  0.1025  2023-08-17 23:59:56.994000

[180000 rows x 3 columns]